export const tournaments = [
    {
        name: 'Deleware Wheelchair Tennis Championships',
        date: 'Sep. 22-24',
        location: 'Wilmington, DE',
        director: 'Kathryn Herel',
        level: 'USTA Level 4 / ITF Level N/A',
        month: 'September',
        going: false,
        complete: true,
    },
    {
        name: 'Lost Mountain Wheelchair Championships',
        date: 'Sep. 22-24',
        location: 'Powder Springs, GA',
        director: 'Tony Oswald',
        level: 'USTA Level 3 / ITF Level N/A',
        month: 'September',
        going: true,
        complete: true,
    },
    {
        name: 'JTCC Wheelchair Championships',
        date: 'Oct. 13-15',
        location: 'College Park, MD',
        director: 'Gabby Hesse',
        level: 'USTA Level 4 / ITF Level N/A',
        month: 'October',
        going: true,
        complete: true,
    },
    {
        name: 'America Championships (Adult National Championships)',
        date: 'Nov. 16-19',
        location: 'McDonough, GA',
        director: 'Harlon Matthews',
        level: 'USTA Level 1 / ITF Level N/A',
        month: 'November',
        going: true,
        complete: true,
    },
    {
        name: 'The Piedmont Area Tennis Association Wheelchair Tennis Open',
        date: 'Dec. 15-17',
        location: 'Charlottesville, VA',
        director: 'Catherine DeSouza',
        level: 'USTA Level 4 / ITF Level N/A',
        month: 'December',
        going: true,
        complete: true,
    },
    {
        name: '2024 Arizona Open Wheelchair',
        date: 'Jan. 19-21',
        location: 'Tuscon, AZ',
        director: 'Mia Hansen',
        level: 'USTA Level 3 / ITF Level N/A',
        month: 'January',
        going: true,
        complete: true, 
    },
    {
        name: 'Cajun Classic USTA',
        date: 'Mar. 7-10',
        location: 'Baton Rouge, LA',
        director: 'Jennifer Edmonson',
        level: 'USTA Level 1 / ITF Level 1',
        month: 'March',
        going: true,
        complete: false, 
    },
    {
        name: '2024 Collegiate Wheelchair National Championship',
        date: 'Apr. 10-13',
        location: 'Lake Nona, FL',
        director: 'Rick Workman',
        level: 'USTA Level N/A / ITF Level N/A',
        month: 'April',
        going: true,
        complete: false, 
    }
];
