export const tournaments = [
    {
        name: 'JTCC Wheelchair Championships',
        date: 'Aug. 29 - Sept. 1',
        location: 'College Park, MD',
        director: 'Gabby Hesse',
        level: 'USTA Level 2',
        month: ['August', 'September'],
        going: true,
        complete: true,
    },
    {
        name: 'The Wheelchair Championships at Kennworth',
        date: 'Oct. 10 - 13',
        location: 'Acworth, GA',
        director: 'Tony Oswald',
        level: 'USTA Level 2',
        month: ['October'],
        going: true,
        complete: true,
    },
    {
        name: 'ITA Qualifiers',
        date: 'Nov. 1 - 3',
        location: 'Tuscaloosa, AL',
        director: 'Tyler Mckay',
        level: 'ITA Event',
        month: ['November'],
        going: true,
        complete: true,
    },
    {
        name: 'Wolverine Open',
        date: 'Nov. 14 - 17',
        location: 'Ann Arbor, MI',
        director: 'Chris Kelley',
        level: 'ITA Event',
        month: ['November'],
        going: true,
        complete: true,
    },
    {
        name: 'Piedmont Area Tennis Association Wheelchair Open',
        date: 'Dec. 13 - 15',
        location: 'Charlottesville, VA',
        director: 'Catherine DeSouza',
        level: 'USTA Level 4',
        month: ['December'],
        going: true,
        complete: true,
    },
    {
        name: 'Alabama Open',
        date: 'Feb. 28 - Mar. 2',
        location: 'Tuscaloosa, AL',
        director: 'Tyler Mckay',
        level: 'ITA Event',
        month: ['February', 'March'],
        going: true,
        complete: false,
    },
    {
        name: 'Cougar Open',
        date: 'Apr. 3 - 6',
        location: 'Houston, TX',
        director: 'Kylie Hornbeck',
        level: 'USTA Level 1 / ITF Series 3',
        month: ['April'],
        going: true,
        complete: false,
    },
    {
        name: 'ITA Wheelchair National Championships',
        date: 'Apr. 10 - 13',
        location: 'Orlando, FL',
        director: 'TBD',
        level: 'ITA Event',
        month: ['April'],
        going: true,
        complete: false,
    }
];
